build,cli: fix compilation iwarning on ARM
On ARM char in unsigned, so the following warning is produced:

~~~~
/home/pi/src/sjs/src/cli/linenoise.c:767:19: error: comparison is always
false due to limited range of data type [-Werror=type-limits]
				if (c < 0) return l.len;
					^
~~~~